### PR TITLE
Add force_reload to *Reference.fetch

### PR DESCRIPTION
**Pull request by lafrech**
Fixes https://github.com/Scille/umongo/issues/91.

(BTW, it looks like the `no_data` parameter has no effect. Is this a TODO?)

### CODE REVIEW

**Comment by touilleMan** [comment]
> (BTW, it looks like the no_data parameter has no effect. Is this a TODO?)

Yep, seems like I put this as a placeholder for future optimization...

**Comment by touilleMan** [comment]
merged, thx for the work 👍

**Comment by lafrech** [comment]
Regarding `no_data` (or `exists`, I saw a comment in the code saying you'd like to rename it to `exists`), it would just need to add a projection to fetch only the `_id` field. What would you like it to return? A `Document` with only `id`? Or a boolean?

**Comment by touilleMan** [comment]
I would say the return type of the function should not changed whether or not we provide `no_data`. So we should always return a `Document`, only passing the `no_data` param would mean all it fields but `_id` are missing (e.i. accessing them result in a `FieldNotLoadedError` exception)

**Comment by lafrech** [comment]
Yes, that's what I thought, too.

**Comment by lafrech** [comment]
What about adding a `projection` parameter to fetch? This would allow any projection possibility.

The `no_data` / `exists` case could be covered by either fetching with explicit `_id`-only projection, or we could introduce a `Reference.check_exists()` method that would do the projection and return a boolean (with `force_reload` to `True`?).

Even then, we'd still have a little performance penalty for the useless instantiation of the `Document`. To avoid this, `check_exists` could use the driver directly to avoid instantiation. I'm not sure this is really important.

**Comment by touilleMan** [comment]
`projection` seems much better idea indeed ;-)

> To avoid this, check_exists could use the driver directly to avoid instantiation. I'm not sure this is really important.

This seems too low level for umongo (you want maximum perf, you do everything by hand using raw pymongo)

**Pull request merged**
