### PR TITLE
fix error due to typo in flask example

### PR DESCRIPTION
**Pull request by mandarup**
- fixes `TypeError: as_marshmallow_schema() missing 1 required positional argument: 'self'`

### CODE REVIEW

**Comment by touilleMan** [comment]
thanks, I've manually merged both of your PRs :+1:

**Comment by mandarup** [comment]
thanks @touilleMan. I wasn't sure how else I could reach you .. Do you have any idea if this project is going to be maintained in foreseeable future?  I am starting out with a project and I am struggling to choose between ODM options. any recommendations/advice?

**Comment by touilleMan** [comment]
@mandarup I've end up creating umongo because mongoengine really was too broken to be fixed, so I obviously don't recommend you this one (I've no experience with other ODM, but they all seemed to be much more SQL inspired ORM than real mongo ODM at the time I was looking for an alternative to mongoengine)
Considering umongo, I'm not planning any big evolution on it, but I'm really open to PR and fixes ;-)

**Comment by mandarup** [comment]
@touilleMan Thanks for your response, it's very valuable to me, much appreciated!!

**Pull request merged**
