### PR TITLE
Marshmallow 3 compatibility

### PR DESCRIPTION
**Pull request by lafrech**
Closes https://github.com/Scille/umongo/issues/129.

The failing test is due to an issue in marshmallow that was fixed since 3.0.0rc1 was released. It'll be fixed with next marshmallow release.

### CODE REVIEW

**Comment by lafrech** [comment]
Updated.

Many failing tests because this is based on latest unreleased commits from dev branch. This will be fixed with next marshmallow release.

**Comment by wfscheper** [comment]
@lafrech, 3.x is out now and it looks like they've addressed a lot of issues with the initial release. If you're otherwise swamped, I can take on cleaning up this pull request.

**Comment by rbu** [comment]
> @lafrech, 3.x is out now and it looks like they've addressed a lot of issues with the initial release. If you're otherwise swamped, I can take on cleaning up this pull request.

That would be much appreciated. I have a code base that uses marshmallow 3 on pymongo directly and I'm evaluating if it makes sense to pull in umongo as an intermediary to get rid of some of our management code.

**Comment by lafrech** [comment]
Indeed, we released MA3 in august and there's been a few fixes since then. Porting to MA3 would be great.

I won't do this right now, but you could start from where I stopped and I could try to find time to review before merging. It's a great changeset so two pairs of eyes won't be a luxury.

**Comment by lafrech** [comment]
I just pushed a rebase of my MA3 port branch. This is still WIP.

@wfscheper, feel free to work on this if you get the time.

To get the tests to pass, I had two fixes in by marshmallow code:

- https://github.com/marshmallow-code/marshmallow/pull/1448 (not merged yet)
- I commented a few lines in Nested._serialize and _deserialize to revert and optim there that breaks our use case. More on this in https://github.com/marshmallow-code/marshmallow/issues/1424.

**Comment by lafrech** [comment]
I pushed a new commit with a patch that makes all tests pass.

I'd rather solve this upstream, though. See https://github.com/marshmallow-code/marshmallow/issues/1424.

**Comment by lafrech** [comment]
Rebased.

We could add the `Pluck` field, which was added in marshmallow 3, but this can be done later in a v3.x.

I'm tempted to release a 3.0.0b1 version and see how it goes.

@wfscheper @Cayke would you like to review / try that branch on your codebase?

**Comment by wfscheper** [comment]
I'll try to look at this tonight.

**Comment by Cayke** [comment]
> Rebased.
> 
> We could add the `Pluck` field, which was added in marshmallow 3, but this can be done later in a v3.x.
> 
> I'm tempted to release a 3.0.0b1 version and see how it goes.
> 
> @wfscheper @Cayke would you like to review / try that branch on your codebase?

Tried in my project and everything looks fine. I only had to refactor my fields because now you cannot set required and default params together.

**Comment by lafrech** [comment]
`as_marshmallow_field` (more precisely `_extract_marshmallow_field_params`) only picks common field parameters.

We should also pick field-specific parameters. Each field can declare an attribute with a list of fields to pick.

I suppose this also affects umong2/marshmallow2 but I never caught got by it.

**Comment by lafrech** [comment]
We should also check that parameters are correctly picked.

See https://github.com/marshmallow-code/marshmallow/issues/1281 and what happens in `_normalize_nested_options`.

It may not be safe to just get the attribute if it was changed in at init.

**Comment by lafrech** [comment]
Or we could extend the `marshmallow_` mechanism to catch all `marshmallow_`-prefixed kwargs, not just a fixed list of expected attributes.

**Comment by lafrech** [comment]
This is illustrated in https://github.com/Scille/umongo/commit/321d951ba3baa088f22db8ad7c23d0f7d2d3647f.

I'm tempted to change the prefix to just `ma_` for concision.

Note to self: Is the "Deserialize default/missing values" phase still needed with MA3?

**Comment by lafrech** [comment]
I removed missing/default deserializaton because in MA3 those come in deserialized form.

This makes it more awkward to pass Dict or List as default, but since passing mutable default is a bad idea, I don't think it is that bad.

**Comment by lafrech** [comment]
@wfscheper, @Cayke, @mymedia2, @Kilo59, I merged this.

There is still a few things to do before shipping umongo 3.

Before releasing a 3.0.0, I think we should release beta versions.

Meanwhile, you can already test master on your codebase and provide feedback.

Thanks.

**Comment by lafrech** [comment]
I released a beta version.

Please try it when you get the time.

Also see https://github.com/Scille/umongo/milestone/1.

**Pull request merged**
