### PR TITLE
Let as_marshmallow_field pass metadata

### PR DESCRIPTION
**Pull request by lafrech**
Sometimes, it is useful to pass a field arbitrary names attributes that are used in the application. Marshmallow supports this and stores those attributes in `Field.metadata`.

For instance, when using Marshmallow + apispec, [API specific parameters](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/swagger.py#L165) can be passed to the `Schema` when declaring the model.

It would be nice to be able to declare those attributes in each uMongo `Field`. It looks as easy as just passing the `metadata` as kwargs when creating the Marshmallow field.

I don't see any drawback to this, except it may pass metadata that was there for uMongo purposes and wasn't meant to trickle down to Marshmallow, but I think Marshmallow will just silently ignore it, this shouldn't be a blocker for that feature.

Here's an implementation proposal. The patch is dead simple.

I added a few tests in test_keep_attributes which was labeled as `TODO`. I hope this is what you had in mind for this function. Otherwise, I can rework this.

### CODE REVIEW

**Comment by lafrech** [comment]
I'm afraid motor 1.0 introduces braking changes (unrelated to this PR).

The good news is they moved to Pymongo 3.

> Motor now depends on PyMongo 3.3 and later. The move from PyMongo 2 to 3 brings
a large number of API changes, read Motor 1.0 Migration Guide and the PyMongo 3
changelog carefully.

**Comment by lafrech** [comment]
I'm afraid motor 1.0 introduces braking changes (unrelated to this PR).

The good news is they moved to Pymongo 3.

> Motor now depends on PyMongo 3.3 and later. The move from PyMongo 2 to 3 brings
a large number of API changes, read Motor 1.0 Migration Guide and the PyMongo 3
changelog carefully.

**Comment by lafrech** [comment]
I'm afraid motor 1.0 introduces braking changes (unrelated to this PR).

The good news is they moved to Pymongo 3.

> Motor now depends on PyMongo 3.3 and later. The move from PyMongo 2 to 3 brings
a large number of API changes, read Motor 1.0 Migration Guide and the PyMongo 3
changelog carefully.

**Comment by lafrech** [comment]
I'm afraid motor 1.0 introduces braking changes (unrelated to this PR).

The good news is they moved to Pymongo 3.

> Motor now depends on PyMongo 3.3 and later. The move from PyMongo 2 to 3 brings
a large number of API changes, read Motor 1.0 Migration Guide and the PyMongo 3
changelog carefully.

**Comment by lafrech** [comment]
I'm afraid motor 1.0 introduces braking changes (unrelated to this PR).

The good news is they moved to Pymongo 3.

> Motor now depends on PyMongo 3.3 and later. The move from PyMongo 2 to 3 brings
a large number of API changes, read Motor 1.0 Migration Guide and the PyMongo 3
changelog carefully.

**Comment by lafrech** [comment]
I'm afraid motor 1.0 introduces braking changes (unrelated to this PR).

The good news is they moved to Pymongo 3.

> Motor now depends on PyMongo 3.3 and later. The move from PyMongo 2 to 3 brings
a large number of API changes, read Motor 1.0 Migration Guide and the PyMongo 3
changelog carefully.

**Comment by lafrech** [comment]
I'm afraid motor 1.0 introduces braking changes (unrelated to this PR).

The good news is they moved to Pymongo 3.

> Motor now depends on PyMongo 3.3 and later. The move from PyMongo 2 to 3 brings
a large number of API changes, read Motor 1.0 Migration Guide and the PyMongo 3
changelog carefully.

**Comment by lafrech** [comment]
I'm afraid motor 1.0 introduces braking changes (unrelated to this PR).

The good news is they moved to Pymongo 3.

> Motor now depends on PyMongo 3.3 and later. The move from PyMongo 2 to 3 brings
a large number of API changes, read Motor 1.0 Migration Guide and the PyMongo 3
changelog carefully.

**Comment by lafrech** [comment]
I'm afraid motor 1.0 introduces braking changes (unrelated to this PR).

The good news is they moved to Pymongo 3.

> Motor now depends on PyMongo 3.3 and later. The move from PyMongo 2 to 3 brings
a large number of API changes, read Motor 1.0 Migration Guide and the PyMongo 3
changelog carefully.

**Comment by touilleMan** [comment]
I've released a new version with motor dependency updated, you can rebase on it

**Comment by lafrech** [comment]
Yep. There you go.

Glad if you like the "feature".

**Pull request merged**
