### PR TITLE
Add fields to EmbeddedDocument.__dir__() to facilitate dynamic code completion

### PR DESCRIPTION
**Pull request by whophil**
I may be misremembering, but I thought this worked at some point in the past.

### CODE REVIEW

**Comment by whophil** [comment]
Failing due to issues addressed by #366 , rerun tests after that is merged.

**Comment by lafrech** [comment]
Thanks for contributing.

I'm not familiar with this. I've read about `dir` today and it looks like overriding `__dir__` is not so common.

Anyway, I have no objection. Should the same be done with `Document`?

**Comment by whophil** [comment]
> I'm not familiar with this. I've read about `dir` today and it looks like overriding `__dir__` is not so common.

To provide some more context - this aids in dynamic auto-completion, so that in IDEs or REPLs that support it (e.g., IPython), dot completion will show you the field names as suggestions, _in addition to_ all the suggestions for `my_document`.

Before:
image

With `__dir__` override
image

> Anyway, I have no objection. Should the same be done with `Document`?

It looks like `Document` already inherits `__dir__` from `EmbeddedDocument`. Also, the test for this capability is actually on `Document` and not `EmbeddedDocument`, so perhaps this is enough as-is.

**Comment by lafrech** [comment]
Oh, right. `Document` inherits it from `EmbeddedDocument`.

Yeah, we could test it on both, but it is not critical.

**Pull request merged**
