### PR TITLE
Fixes broken to_list in motor_asyncio WrappedCursor class

### PR DESCRIPTION
**Pull request by halfdanrump**
Refs https://github.com/Scille/umongo/issues/197

### CODE REVIEW

**Comment by lafrech** [comment]
This is a duplicate of https://github.com/Scille/umongo/pull/184/files.

**Comment by halfdanrump** [comment]
Sorry, I didn't mean to include the modifications to `__repr__` in the PR. I'll revert and branch.

**Comment by lafrech** [comment]
#184 targets the same goal and is more advanced. I don't think it is worth working on another PR.

**Comment by halfdanrump** [comment]
@lafrech My bad! I'll close the PR.

**Pull request closed without merging**
