### PR TITLE
Fix find/find_one: pass filter as first positional arg

### PR DESCRIPTION
**Pull request by lafrech**

### CODE REVIEW

**Comment by lafrech** [comment]
@wfscheper I intend to merge and release this bugfix. Any objection? I modified async code, so you may want to double-check.

**Comment by wfscheper** [comment]
Hopefully, I can take a look at it tonight, but if I don't get back to you
after tomorrow then go ahead and merge it.

**Comment by lafrech** [comment]
No pb. No rush. Thanks.

**Comment by lafrech** [comment]
Thanks for double-checking. I merged and released.

**Pull request merged**
